# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 67eb05bf9495950ca31c6a078d69c8c75d7ccd4fcf6de0dcf1c3a033f0144ba505b34db965795b112a4baf4205c5684ee2f1bd42ac22cb5590d5d4cc256f9994

test:
  secret_key_base: 4a8868938141e121afa230c0dfccfe62d42452483d1b21fcd905c92e2af12f02615ea5e56b2840ea316628c47a0f33ca058c912ee473e21611c78fbd7713dca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
